version: "3.9"  # use what version you need
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - backend
    depends_on:
      - backend

  backend:
    image: dadarek/wait-for-dependencies
    build:
      context: ../../
      dockerfile: docker/Dockerfile.allMicroServices
    env_file:
      - .env
    ports:
      - 3333:3333
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=master123
      - POSTGRES_DB=puppilots
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  pg_data:
    driver: local
