apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kube-files
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kube-files
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/scripts-backend: "true"
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: FILE
              value: .env.backend
          image: raomaster/puppilots-backend:latest
          name: backend
          ports:
            - containerPort: 3333
              hostPort: 3333
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
