apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kube-files
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
  namespace: default
spec:
  ports:
    - name: "3333"
      port: 3333
      targetPort: 3333
  selector:
    io.kompose.service: backend
status:
  loadBalancer: {}
